<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>CTranslator</RootNamespace>
    <AssemblyName>CTranslator</AssemblyName>
  </PropertyGroup>
</Project>
